services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: always
    command:
      - --config=/etc/otelcol-cont/otel-collector.yml
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/otelcol-cont/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    hostname: tempo
    ports:
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
    volumes:
      - ./docker/grafana-config/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    command: |
      -config.file=/etc/tempo.yaml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - tempo
    restart: always

  netutils:
    image: dersimn/netutils
    container_name: netutils
    restart: always
    entrypoint: tail -f /dev/null